/*
 * Pin engine.js to the Python reference agents.
 *
 *   node tests/run_crosscheck.js
 *
 * crosscheck.json is committed, so this needs node and nothing else. It is
 * generated by weakc4/gen_js_crosscheck.py in the connect4 research repository,
 * which is where the Python reference lives.
 *
 * Any mismatch is a hard failure: the page's agent must be indistinguishable
 * from verify_strict.py, or a diagram that "verifies" in the browser means
 * nothing.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const W = require('../engine.js');

const fixturePath = path.join(__dirname, 'crosscheck.json');
if (!fs.existsSync(fixturePath)) {
  console.error('missing ' + fixturePath +
                '\nit is committed; regenerate with weakc4/gen_js_crosscheck.py' +
                '\nin the connect4 research repository');
  process.exit(2);
}
const fx = JSON.parse(fs.readFileSync(fixturePath, 'utf8'));

let failures = 0;
const show = (msg) => { if (failures < 10) console.error('  ' + msg); };

function boardOf(rep) {
  const p = W.parseRep(rep);
  if (p.error) throw new Error(p.error);
  const b = W.boardFromMoves(p.moves);
  if (b.error) throw new Error(b.error);
  return b.board;
}

// ---- decisions -------------------------------------------------------------
let strictBad = 0;
for (let i = 0; i < fx.decisions.length; i++) {
  const c = fx.decisions[i];
  const s = W.decide(boardOf(c.rep), c.diagram).move;
  if (s !== c.strict) {
    strictBad++; failures++;
    show(`decide #${i} rep=${c.rep} js=${s} py=${c.strict}\n    ${c.diagram.join('\n    ')}`);
  }
}

/*
 * One deliberate divergence: engine.js refuses a root that already contains a
 * four-in-a-row (reason ROOT_TERMINAL), whereas verify_ss_strict happily
 * searches from one and reports a win. The generator never produces such a
 * position, so this comparison stays clean; if a future fixture does, the JS
 * is the correct side.
 */
// ---- exhaustive verification ----------------------------------------------
let verifyBad = 0;
for (let i = 0; i < fx.verifies.length; i++) {
  const c = fx.verifies[i];
  const res = W.verify(boardOf(c.rep), c.diagram, {});
  if (res.overflow) { verifyBad++; failures++; show(`verify #${i} rep=${c.rep} hit the node budget`); continue; }
  if (res.win !== c.win) {
    verifyBad++; failures++;
    show(`verify #${i} rep=${c.rep} js=${res.win} py=${c.win}`);
  }
}

// ---- round-trips -----------------------------------------------------------
let codecBad = 0;
for (let i = 0; i < fx.decisions.length; i++) {
  const d = fx.decisions[i].diagram.map((r) => r.replace(/ /g, '.'));
  const back = W.decodeDiagram(W.encodeDiagram(d));
  if (!back || back.join('\n') !== d.join('\n')) { codecBad++; failures++; show(`codec #${i} round-trip changed the diagram`); }
}

// ---- importer --------------------------------------------------------------
let importBad = 0;
for (let i = 0; i < Math.min(400, fx.decisions.length); i++) {
  const c = fx.decisions[i];
  const norm = c.diagram.map((r) => r.replace(/ /g, '.'));
  const asJson = JSON.stringify({ rep: c.rep, diagram: norm });
  const viaJson = W.parseImport(asJson);
  if (viaJson.error || W.repString(viaJson.moves) !== c.rep || viaJson.diagram.join() !== norm.join()) {
    importBad++; failures++; show(`import(JSON) #${i}: ${viaJson.error || 'round-trip changed'}`);
    continue;
  }
  // Grid alone: the position must be recoverable from the '1'/'2' stones.
  const viaGrid = W.parseImport(norm.join('\n'));
  if (viaGrid.error) { importBad++; failures++; show(`import(grid) #${i}: ${viaGrid.error}`); continue; }
  const want = boardOf(c.rep);
  const got = W.boardFromMoves(viaGrid.moves).board;
  if (W.bkey(want) !== W.bkey(got)) { importBad++; failures++; show(`import(grid) #${i}: rebuilt a different position`); }
}

// ---- importer regressions --------------------------------------------------
//
// Malformed and ambiguous input, each from a bug that shipped. The random
// fixture above only ever feeds the importer well-formed data, so it cannot
// catch any of these.
let regressBad = 0;
const ROWS6 = ['...@...', '...1...', '+@.2=..', '+!.1=..', '+1-2=..', '22-1=..'];
const REGRESSIONS = [
  // A present-but-malformed diagram used to be dropped in silence, so a
  // truncated artifact imported as a success while keeping the old diagram.
  ['JSON with 5 diagram rows is rejected',
   () => !!W.parseImport(JSON.stringify({ rep: '44444221', diagram: ROWS6.slice(1) })).error],
  ['JSON with a non-array diagram is rejected',
   () => !!W.parseImport('{"rep":"44444221","diagram":"nope"}').error],
  ['JSON with a good diagram still loads',
   () => W.parseImport(JSON.stringify({ rep: '44444221', diagram: ROWS6 })).diagram !== null],
  // Seven digits drawn only from columns 1 and 2 are also a legal row of
  // stones. One such line with no other rows is a rep, not a diagram.
  ['a 7-move rep of columns 1 and 2 loads as a rep',
   () => { const r = W.parseImport('1211212'); return !r.error && r.moves.length === 7; }],
  ['a 7-move rep of columns 1, 2 and 3 loads as a rep',
   () => { const r = W.parseImport('1123212'); return !r.error && r.moves.length === 7; }],
  // The rule it must not break: a row is never trimmed, because claimeven is a
  // space on disk and "   1   " is a legitimate row rather than a move.
  ['six diagram rows still parse as a diagram',
   () => { const r = W.parseImport(ROWS6.join('\n')); return !r.error && r.diagram !== null; }]
];
for (const [name, fn] of REGRESSIONS) {
  let ok = false;
  try { ok = fn(); } catch (e) { ok = false; }
  if (!ok) { regressBad++; failures++; show(`regression: ${name}`); }
}

const n = fx.decisions.length;
console.log(`decisions : ${n} agent moves       mismatches: ${strictBad}`);
console.log(`verify    : ${fx.verifies.length} exhaustive        mismatches: ${verifyBad}`);
console.log(`codec     : ${n} round-trips        mismatches: ${codecBad}`);
console.log(`import    : ${Math.min(400, n)} JSON + grid       mismatches: ${importBad}`);
console.log(`regression: ${REGRESSIONS.length} importer cases     mismatches: ${regressBad}`);
console.log(`reference : ${JSON.stringify(fx.reference)}`);

if (failures) {
  console.error(`\nFAILED with ${failures} mismatch(es)`);
  process.exit(1);
}
console.log('\nOK - engine.js matches the Python reference on every case.');
